[project]
name = "omnisift"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Abdul Rehman Khan", email = "thewilyde@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aioboto3>=15.5.0",
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "boto3>=1.40.61",
    "fastapi>=0.142.2",
    "greenlet>=3.5.6",
    "passlib[bcrypt]>=1.7.4",
    "pgvector>=0.5.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.4",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
    "sqlalchemy>=2.1.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
omnisift = "omnisift:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
